apiVersion: batch/v1
kind: CronJob
metadata:
  name: genet-cleanup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cleanup.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: genet-cleanup
        spec:
          serviceAccountName: genet-backend
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: {{ .Values.cleanup.image }}
            command: ["/app/cleanup"]
            volumeMounts:
            - name: config
              mountPath: /etc/genet
          volumes:
          - name: config
            configMap:
              name: genet-config
