apiVersion: batch/v1
kind: CronJob
metadata:
  name: genet-cleanup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cleanup.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: genet-cleanup
        spec:
          serviceAccountName: genet-backend
          restartPolicy: OnFailure
          {{- with .Values.cleanup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cleanup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: cleanup
            image: "{{ .Values.cleanup.image.repository }}:{{ .Values.cleanup.image.tag | default .Chart.AppVersion }}"
            command: ["/app/cleanup"]
            volumeMounts:
            - name: config
              mountPath: /etc/genet
          volumes:
          - name: config
            configMap:
              name: genet-config
